### ISSUE TITLE
How to use Bottleneck layer?

### ISSUE THREAD

**Issue by kayuksel** [microsoft/IBAC-SNI#1]
Hello, thanks for sharing this impressive work. I would be more than glad if you can explain how to use the proposed Bottleneck layer, as it is a bit difficult to understand that from the current code / paper e.g. where the Bottleneck layer should be placed in a Deep Learning architecture? It would be great to include a small toy example that demonstrates the usage. Sincerely, Kamer

**Comment by maximilianigl** [comment]
In our experiments, the bottleneck layer is placed second to last in the architecture, just before the value and policy heads of the network. For the layer itself, we follow the implementation proposed by A. Alemi, e.g. see here: https://github.com/alexalemi/vib_demo.

In our code, the implementation of the bottleneck can be seen well in the Multiroom environment, e.g. see [here](https://github.com/microsoft/IBAC-SNI/blob/684faecfecb14de4101f626a863d79e74ae9cce3/torch_rl/bottleneck.py#L20) for the implementation of the layer and [here](https://github.com/microsoft/IBAC-SNI/blob/684faecfecb14de4101f626a863d79e74ae9cce3/torch_rl/model.py#L192) for how it's used. We additionally return the mean (not only the sampled value), as we need it for the SNI implementation.

Hope that helps. Let me know if you have any further questions.
