### ISSUE TITLE
Diverging results from those in the paper

### ISSUE THREAD

**Issue by mahenning** [microsoft/IBAC-SNI#5]
Hi,
I ran the commands for IBAC, IBAC-SNI and NoReg from the Readme two times for 100 million steps, and I got the results below. 
Do you have an idea why 
(a) my return for IBAC is so much higher than in the paper and
(b) the return for IBAC-SNI is so low?

I know that training for only two times isn't much but at least for the two IBAC variants the variance was almost non-existent.
Sincerely, Marko

<img src="https://user-images.githubusercontent.com/7490102/82197623-8099d580-98fb-11ea-8c84-76bd256e06d2.png" width = 500>
<img src="https://user-images.githubusercontent.com/7490102/82197633-82fc2f80-98fb-11ea-9e49-a32dab68ac8d.png" width = 500>

**Comment by maximilianigl** [comment]
Hi Marko,

unfortunately, the fully observable Multiroom environment I'm using here is extremely noisy and the results are bi-modal, i.e. either it learns or it does not (at all). In the paper I'm therefore averaging over 30 seeds and plotting the standard _error_, i.e. the std/sqrt(30). 
With just two random seeds, I'd say it's quite possible that you just were lucky for IBAC and unlucky for IBAC-SNI.
When I was working on it, I was using about 5-8 seeds and plotting the median & max. It's still very noisy, but I found that to be a decent intermediate solution for faster iteration speed and somewhat meaningful results. 
Best, Max

**Comment by maximilianigl** [comment]
I'm closing this for now, but please let me know if you have further questions.
