### ISSUE TITLE
What is create_saliency.py

### ISSUE THREAD

**Issue by KaiyangZhou** [microsoft/IBAC-SNI#7]
Could you give a brief explanation for `create_saliency.py` and how it should be used? Thanks

**Comment by maximilianigl** [comment]
It was used to create saliency plots under different regularization methods. But I didn't find the images very insightful, so I didn't pursue it further nor put them into the paper. 
The code might need a few adaptations to work - not sure, I haven't looked at it in a while.
In case it doesn't work right out of the box and you make it work, it would be great if you have the time for a PR.

**Comment by KaiyangZhou** [comment]
cool, thanks for your explanation
