### ISSUE TITLE
The agent learn nothing in Grid-world environment

### ISSUE THREAD

**Issue by liuqi8827** [microsoft/IBAC-SNI#9]
Hi
Thanks your great work.
I'm facing a problem of the visualization performence of the agent in Grid-world environment.
I train the agent successfully. 
However, I found the agent learn nothing in Grid-world environment by **visualize.py**.
The agent chose it's action rundamly. It never success!

1. I run `python -m scripts.train --frames 100000000 --algo ppo --env MiniGrid-MultiRoom-N3r-v0 --model N3r-vib1e6 --save-interval 100 --tb --fullObs --model_type default2 --use_bottleneck --beta 0.000001`
And I got the model parameter in the folder **/storage/N3r-vib1e6**
2. I run `python -m scripts.train --frames 100000000 --algo ppo --env MiniGrid-MultiRoom-N3r-v0 --model N3r-vibS1e6 --save-interval 100 --tb --fullObs --model_type default2 --use_bottleneck --beta 0.000001 --sni_type vib`
And I got the model parameter in the folder **/storage/N3r-vibS1e6**
3. I run `plots.py`
And I got the picture below:
![Figure_1](https://user-images.githubusercontent.com/45791783/98458991-19d1e680-21d1-11eb-90a0-c41003c8c79e.png)
4. We can find that the return in step 3 is increase monotonously.
However, when I run `visualize.py` for **N3r-vib1e6** and **N3r-vibS1e6** respectively, I found the agent learn nothing in Grid-world environment. The agent chose it's action rundamly. It never success!

Can you give some suggestions?

Thanks a lot!

**Comment by maximilianigl** [comment]
Hey, 

thank you for the detailed description! 
Just to check first, are you passing `--fullObs` to visualize.py as well?

**Comment by liuqi8827** [comment]
Thanks for your quick reply

You are right. I did not pass `--fullObs` to visualize.py. 
When I run `python3 -m scripts.visualize --env MiniGrid-MultiRoom-N3r-v0 --model N3r-vib1e6 --fullObs`, it works well.

Thanks a lot!

**Comment by maximilianigl** [comment]
Great! I'm closing this, but let me know if you have any other questions!

**Comment by maximilianigl** [comment]
Great! I'm closing this, but let me know if you have any other questions!
